from desk import Desk

peter_game =Desk()
peter_game.shuffle()
#peter_game.print_all()

peter_game.setup_player("Peter")
peter_game.setup_player("Sally")
peter_game.setup_table()
#peter_game.print_table()

#peter_game.Players[0].take_coin([0,0,0,0,0,1])
peter_game.take_coin(peter_game.Players[0],[0,2,0,0,0])
#peter_game.print_table()
peter_game.take_coin(peter_game.Players[0],[1,1,1,1,0])
#peter_game.print_table()
peter_game.take_coin(peter_game.Players[0],[0,1,1,1,0])
#peter_game.print_table()
peter_game.take_coin(peter_game.Players[0],[0,2,0,0,0])
#peter_game.print_table()
peter_game.take_coin(peter_game.Players[0],[0,0,1,0,2])
peter_game.take_coin(peter_game.Players[0],[0,0,1,1,1])
peter_game.take_coin(peter_game.Players[0],[0,1,1,1,0])
peter_game.take_coin(peter_game.Players[0],[0,1,1,1,0])
peter_game.return_coin(peter_game.Players[0],[0,0,0,0,0])
peter_game.print_table()
